spring:
  main:
    allow-bean-definition-overriding: false
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate: info
      hibernate.SQL: debug
      hibernate.cache: debug
app:
  scheduler:
    process-transactions: '-' # disabled for testing purposes

