spring:
  application:
    name: inghubs-digital-wallet
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  main:
    allow-circular-references: false
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      jdbc:
        schema-initialization:
          enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/example_ing_test_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 30000
  flyway:
    enabled: true
  messages:
    basename: i18n/messages
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

app:
  scheduler:
    process-transactions: '*/5 * * * * *'
  wallet:
    transaction:
      max-allowed-amount: 1000
  jwt:
    secret-key: 014bd140b8282de5dec2ceb1208832b8
    expiration-in-ms: 2592000000
  kafka:
    notificationGroupId: ing-transaction-notification-id
    groupId: ing-demo-case-group-id
    bootstrapServers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    transactionTopic: transaction-topic
